name: ECM Distro Tools Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build ECM Distro Tools
        run: |
          export VERSION=${GITHUB_REF_NAME}
          make test
          make package-binaries
      - name: Publish Binaries
        uses: SierraSoftworks/gh-releases@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: "true"
          files: |
            ${{ github.workspace }}/cmd/release/bin/release-darwin-amd64
            ${{ github.workspace }}/cmd/release/bin/release-darwin-arm64
            ${{ github.workspace }}/cmd/release/bin/release-freebsd-amd64
            ${{ github.workspace }}/cmd/release/bin/release-freebsd-arm64
            ${{ github.workspace }}/cmd/release/bin/release-linux-amd64
            ${{ github.workspace }}/cmd/release/bin/release-linux-arm64
            ${{ github.workspace }}/cmd/release/bin/sha256sums-release.txt
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rancher/ecm-distro-tools:${{ github.ref_name }}
          file: ./Dockerfile
          context: .
