name: ECM Distro Tools Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build ECM Distro Tools
        run: |
          export VERSION=${GITHUB_REF_NAME}
          make test
          make package-binaries
      - name: Publish Binaries
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload -R ${{ github.repository }} ${{ github.ref_name }} ${{ github.workspace }}/dist/* --clobber
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Build and push image
        run: |
          IID_FILE=$(mktemp)
          IID_FILE_FLAG="--iidfile ${IID_FILE}" make push-image
          cosign sign --oidc-provider=github-actions --yes "${REPO}@$(head -n 1 ${IID_FILE})"
        env:
          TAG: ${{ github.ref_name }}
          REPO: rancher/ecm-distro-tools
