name: Transfer Rancher artifacts to prime bucket
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "e.g: v2.8.4"
        required: true
      base_registry:
        type: choice
        description: "registry where the images were first uploaded to"
        options:
          - "docker.io"
          - "stgregistry.suse.com"
          - "registry.rancher.com"
        required: true
      rancher_repo_owner:
        type: string
        description: "org that the rancher repo is located in"
        default: "rancher"
        required: false
      prime_artifacts_bucket:
        type: string
        description: "name of the bucket to upload the files"
        default: "prime-artifacts"
        required: false
jobs:
  transfer:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: setup ecm-distro-tools
        uses: rancher/ecm-distro-tools@v0.36.0
        with:
          version: v0.36.0
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/prime-artifacts-uploader-access-key/credentials token | PRIME_ARTIFACTS_UPLOADER_ACCESS_KEY ;
            secret/data/github/repo/${{ github.repository }}/prime-artifacts-uploader-secret-key/credentials token | PRIME_ARTIFACTS_UPLOADER_SECRET_KEY ;
      - name: Create aws credentials file
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $PRIME_ARTIFACTS_UPLOADER_ACCESS_KEY" >> ~/.aws/credentials
          echo "aws_secret_access_key = $PRIME_ARTIFACTS_UPLOADER_SECRET_KEY" >> ~/.aws/credentials
      - name: Create ecm config file 
        run: |
          mkdir -p ~/.ecm-distro-tools
          echo "{\"rancher\":{\"versions\":{\"${{ github.event.inputs.tag }}\":{\"dry_run\":false,\"rancher_repo_owner\":\"${{ github.event.inputs.rancher_repo_owner }}\",\"base_registry\":\"${{ github.event.inputs.base_registry }}\",\"registry\":\"registry.rancher.com\",\"prime_artifacts_bucket\":\"${{ github.event.inputs.prime_artifacts_bucket }}\"}}}}" > ~/.ecm-distro-tools/config.json
      - name: Transfer artifacts
        run: release upload rancher artifacts ${{ github.event.inputs.tag }}
  digests:
    needs: [transfer]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: setup ecm-distro-tools
        uses: rancher/ecm-distro-tools@v0.36.0
        with:
          version: v0.36.0
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/prime-artifacts-uploader-access-key/credentials token | PRIME_ARTIFACTS_UPLOADER_ACCESS_KEY ;
            secret/data/github/repo/${{ github.repository }}/prime-artifacts-uploader-secret-key/credentials token | PRIME_ARTIFACTS_UPLOADER_SECRET_KEY ;
      - name: Create ecm config file 
        run: |
          mkdir -p ~/.ecm-distro-tools
          release config gen
      - name: Generate Linux Digests
        run: |
          mkdir -p dist
          release generate rancher docker-images-digests \
            --artifact-url "https://github.com/${{ github.event.inputs.rancher_repo_owner }}/rancher/releases/download/${{ github.event.inputs.tag }}/rancher-images.txt" \
            --output-file ./dist/rancher-images-digests-linux-amd64.txt \
            --registry "${{ github.event.inputs.base_registry }}"
          cp ./dist/rancher-images-digests-linux-amd64.txt ./dist/rancher-images-digests-linux-arm64.txt
      - name: Generate Windows Digests
        run: |
          release generate rancher docker-images-digests \
            --artifact-url "https://github.com/${{ github.event.inputs.rancher_repo_owner }}/rancher/releases/download/${{ github.event.inputs.tag }}/rancher-windows-images.txt" \
            --output-file ./dist/rancher-images-digests-windows-1809.txt \
            --registry "${{ github.event.inputs.base_registry }}"
          cp ./dist/rancher-images-digests-windows-1809.txt ./dist/rancher-images-digests-windows-ltsc2022.txt
      - name: Create aws credentials file
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $PRIME_ARTIFACTS_UPLOADER_ACCESS_KEY" >> ~/.aws/credentials
          echo "aws_secret_access_key = $PRIME_ARTIFACTS_UPLOADER_SECRET_KEY" >> ~/.aws/credentials
      - name: Upload Artifacts
        run: |
          aws s3 cp --recursive ./dist s3://${{ github.event.inputs.prime_artifacts_bucket }}/rancher/${{ github.event.inputs.tag }}
